# Generated by Django 4.0.3 on 2022-03-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='base',
            field=models.TextField(blank=True, null=True),
        ),
    ]
