# Generated by Django 4.0.3 on 2022-03-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='poste',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
