# Generated by Django 4.0.3 on 2022-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_me_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='annee',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
